version : '3.1'
services:
    mysql:
      image: mysql:5.7
      container_name: mysql
      environment:
    #    We cannot set user as 'root' if mysql is below version of 5.x: https://github.com/docker-library/mysql/issues/129
        MYSQL_USER: 'matcheo'
        MYSQL_PASSWORD: '2005'
        MYSQL_DATABASE: 'MatcheoAltice'
        MYSQL_ROOT_PASSWORD: '2005'
      ports:
        - "3306:3306"
      volumes:
        #- ./data/conf.d:/etc/mysql/conf.d
        - ./data/logs:/logs
        - ./data/var/mysql:/var/lib/mysql